name: CacheAction

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: test action
    steps:
      - name: Cache Primes
        id: cache-primes
        uses: actions/cache@v3
        with:
          path: ./node_modules/wrappy
          key: dist
      - name: Generate Prime Numbers
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: echo 'cache not hit'
